apiVersion: v1alpha1
metadata:
  name: thanhnq
rendezvousIP: 192.168.68.14
hosts:
  - hostname: master01.thanhnq.vnlabs.dev
    interfaces:
     - name: ens192
       macAddress: 00:50:56:87:94:a1
    networkConfig:
      interfaces:
        - name: ens192
          type: ethernet
          state: up
          mac-address: 00:50:56:87:94:a1
          ipv4:
            enabled: true
            address:
              - ip: 192.168.68.14
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 192.168.67.3
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.68.254
            next-hop-interface: ens192
  - hostname: master02.thanhnq.vnlabs.dev
    interfaces:
     - name: ens192
       macAddress: 00:50:56:87:94:a2
    networkConfig:
      interfaces:
        - name: ens192
          type: ethernet
          state: up
          mac-address: 00:50:56:87:94:a2
          ipv4:
            enabled: true
            address:
              - ip: 192.168.68.12
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 192.168.67.3
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.68.254
            next-hop-interface: ens192
  - hostname: master03.thanhnq.vnlabs.dev
    interfaces:
     - name: ens192
       macAddress: 00:50:56:87:94:a3
    networkConfig:
      interfaces:
        - name: ens192
          type: ethernet
          state: up
          mac-address: 00:50:56:87:94:a3
          ipv4:
            enabled: true
            address:
              - ip: 192.168.68.13
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 192.168.67.3
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.68.254
            next-hop-interface: ens192
  - hostname: worker01.thanhnq.vnlabs.dev
    interfaces:
     - name: ens192
       macAddress: 00:50:56:87:94:b1
    networkConfig:
      interfaces:
        - name: ens192
          type: ethernet
          state: up
          mac-address: 00:50:56:87:94:b1
          ipv4:
            enabled: true
            address:
              - ip: 192.168.68.21
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 192.168.67.3
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.68.254
            next-hop-interface: ens192            
  - hostname: worker02.thanhnq.vnlabs.dev
    interfaces:
     - name: ens192
       macAddress: 00:50:56:87:94:b2
    networkConfig:
      interfaces:
        - name: ens192
          type: ethernet
          state: up
          mac-address: 00:50:56:87:94:b2
          ipv4:
            enabled: true
            address:
              - ip: 192.168.68.22
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 192.168.67.3
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.68.254
            next-hop-interface: ens192            
 
            

