kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: bastion.demolab.local:8443/ocp4/openshift4/mirror/oc-mirror-metadata
    skipTLS: false
mirror:
  platform:
    channels:
    - name: stable-4.12
      type: ocp
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.13
    packages:
    - name: serverless-operator
      channels:
      - name: stable
    - name: advanced-cluster-management
      channels:
      - name: release-2.7
    - name: cluster-logging
      channels:
      - name: stable
    - name: container-security-operator
      channels:
      - name: stable-3.8
    - name: eap
      channels:
      - name: stable
    - name: elasticsearch-operator
      channels:
      - name: stable
    - name: loki-operator
      channels:
      - name: stable
    - name: mcg-operator
      channels:
      - name: stable-4.12
    - name: node-healthcheck-operator
      channels:
      - name: stable
    - name: node-maintenance-operator
      channels:
      - name: stable
    - name: odf-csi-addons-operator
      channels:
      - name: stable-4.12
    - name: odf-operator
      channels:
      - name: stable-4.12
    - name: openshift-custom-metrics-autoscaler-operator
      channels:
      - name: stable
    - name: rhacs-operator
      channels:
      - name: latest
    - name: redhat-oadp-operator
      channels:
      - name: stable-1.1
    - name: rh-service-binding-operator
      channels:
      - name: stable
    - name: rhacs-operator
      channels:
      - name: latest
    - name: rhsso-operator
      channels:
      - name: stable
    - name: sandboxed-containers-operator
      channels:
      - name: stable-1.3
    - name: self-node-remediation
      channels:
      - name: stable
    - name: openshift-gitops-operator
      channels:
      - name: latest    
    - name: web-terminal
      channels:
      - name: fast
    - name: compliance-operator
      channels:
      - name: release-0.1    
  additionalImages:
  - name: registry.redhat.io/ubi8/ubi:latest
  helm: {}
