apiVersion: v1
baseDomain: demolab.local
# Neu he thong dung proxy thi chung ta can khai bao ơ day
#proxy:
#  httpProxy: http://proxy.vnlabs.dev:8080
#  httpsProxy: https://USERNAME:PASSWORD@proxy.example.com:PORT
#  noProxy: <WILDCARD_OF_DOMAIN>,<PROVISIONING_NETWORK/CIDR>,<BMC_ADDRESS_RANGE/CIDR>
#  ## example: 
#  noProxy: .thanhnq.vnlabs.dev, 192.168.67.0/24

compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  replicas: 2
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: tinnguyen
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.67.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  baremetal:
    hosts:
      - name: worker01
        role: worker
        bootMACAddress: 00:50:56:bd:ab:12
      - name: worker02
        role: worker
        bootMACAddress: 00:50:56:bd:d9:02
      - name: master01
        role: master
        bootMACAddress: 00:50:56:bd:aa:74
      - name: master02
        role: master
        bootMACAddress: 00:50:56:bd:e9:1c
      - name: master03
        role: master
        bootMACAddress: 00:50:56:bd:83:5a
    apiVIP: "192.168.67.126" # if v4.12, apiVIP --> apiVIPs
    ingressVIP: "192.168.67.127" # if v4.12, ingressVIP --> ingressVIPs
pullSecret: '{"auths": { "bastion.demolab.local:8443": {"auth": "aW5pdDpkNGhTNm1CTTE1Nzl5OEQzYTJjRUFLenVldlliUTBzRw=="}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+jL536WZNQ+hqRpxU0I+uBBSBm1XIVaM7vVJrTMrYbRbb8SxH3CDI6g+ZhozcN346pqVbkMa+XxXqzjQaQGFJOvb/n3hIZkU8VfzdtlEbQ4H1oKXzCuL4QB+uy+2KtEQwSXVemOCy8s3fQBD8TV88Bxqvtcg0RySbcqdfD2p/sJqa1YhXgDKf+pP6iyDTUpUQyLqkkF3UFBkzKhf8R9zPS+SVMXQUDCxI8DTaz04H9FY/7jayST4/UI52ZROia8DQuP/f99by/VS/leztXfNcCNA3nhbf10CBjBN1dlrqdTrGy/U1pLlStVJ4WO3UjATf8FBLHjkSGRNrBIoHqaMB0GCkreK3R+R+ntTZPBHnsdh4cBylVKgtqZ9BAzwx0CHnmFA5+ZQo6vUNxqS0pT4D4XzE6/e01PVXsmk/CJV1kmngjg6C0bZEwfavCoX2fs9AanprgmxbX3w5aWXfYRHRwTvjrhOF5t7PpC8i0oFhhSRZIs+CN3m/dpSP2WoeJYU= tinnguyen@bastion.demolab.local' 
imageContentSources:
- mirrors:
  - bastion.demolab.local:8443/openshift/release
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
- mirrors:
  - bastion.demolab.local:8443/openshift/release-images
  source: quay.io/openshift-release-dev/ocp-release
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
    MIIDxjCCAq6gAwIBAgIUY7mZd+wt/NPZcWM5oHQOyOkVmtowDQYJKoZIhvcNAQEL
    BQAwbzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
    azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xHjAcBgNVBAMMFWJh
    c3Rpb24uZGVtb2xhYi5sb2NhbDAeFw0yMzAzMjAxNjI3NTlaFw0yNjAxMDcxNjI3
    NTlaMG8xCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJWQTERMA8GA1UEBwwITmV3IFlv
    cmsxDTALBgNVBAoMBFF1YXkxETAPBgNVBAsMCERpdmlzaW9uMR4wHAYDVQQDDBVi
    YXN0aW9uLmRlbW9sYWIubG9jYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQDMF0A+2y5/fUKvDfINjBqU4BhNmymjfV/1y6aWBJ3T8scO4j987X8wukV1
    sY9WR5K7f1hrBSBu0vwR9WaaHk7J+NHs+rQi/z1bfjb59wDr52/14ToXTRto9kO3
    LwXRtdA68B/uvR65+hB+JTPGmuRKNO4uPCGS6CRyVaVs3S1PGXiBF37f7Hc96V8c
    4rIhZBhgjPRnoLX9kkNYDcdGavc1jV+FVnbZwS2CNc7hH+0o9hCnJxpPMrCp9M8I
    6LYOFCqvZ+PyoVTxv+k9m2gInmYxcJSdOIRi84oYKEkrS0R4ozt2XgseOLr7aYSX
    tyaAEFWhqw+wuziX96khf4dprjctAgMBAAGjWjBYMAsGA1UdDwQEAwIC5DATBgNV
    HSUEDDAKBggrBgEFBQcDATAgBgNVHREEGTAXghViYXN0aW9uLmRlbW9sYWIubG9j
    YWwwEgYDVR0TAQH/BAgwBgEB/wIBATANBgkqhkiG9w0BAQsFAAOCAQEASVSbEXiI
    9CMxH5MHmjc5rvQVsIb0AK97qrHnOT8Whft6g7ohwUr0gn92n2nT7BMuDRjdSxqV
    x9935rqlJca60DKEGzUhJJ5oeu7jtV9+qRFJEWmaR7GmOJGVp/9DuTymk4JM37kH
    KI7vRoIG/D62Wo829qyh3RR6e4dpiOjSWp0WQmFErjIynHhwdnHRYiFcJL5BfaCy
    uX//8aoiVIeUtdqVGLcqW8ScRLUhtfV1qckwUZMEZ90bZ82/gYxkI8/WiqidJKPl
    W2a6jQw0JpJPAO4b65xp+Bx2+6GzqGPoAj1Hl1ghw+VYWaudoNZO5VXe4KWTHf9q
    gNnOXTCL16LOAg==
    -----END CERTIFICATE-----



